spring:
  main:
    banner-mode: OFF
  application:
    name: "config-server"
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: "/home/admin/Desktop/nash-training/backend/configuration-yml-files"
#        git:
#          uri: "https://github.com/huuhungiu17031/configuration-yml-files.git"
#          default-label: main
#          timeout: 5
#          clone-on-start: true
#          force-pull: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

server:
  port: 8071
